train: 
  batch_size_per_gpu: 32
  OFFICIAL_EPOCH_LENGTH: 450
  cell_augmentation: true
  channel_adaptive: true
student:
  arch: vit_large
  patch_size: 16
  num_register_tokens: 0
  interpolate_antialias: false
  interpolate_offset: 0.1
  drop_path_rate: 0.1
  in_chans: 1
  block_chunks: 4
  channel_adaptive: true
teacher:
  momentum_teacher: 0.996
  warmup_teacher_temp_epochs: 20
  in_chans: 1
  channel_adaptive: true
crops:
  global_crops_scale:
  - 0.4
  - 1.0
  local_crops_number: 8
  local_crops_scale:
  - 0.005
  - 0.4
  global_crops_size: 224
  local_crops_size: 96
optim:
  weight_decay_end: 0.2
  base_lr: 5.0e-4 
  warmup_epochs: 20
  epochs: 400